// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/apigee/EnvironmentKeyvaluemapsEntries.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/list_resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package apigee

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/hashicorp/terraform-provider-google/google/registry"
	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google/google/transport"
)

func init() {
	registry.FrameworkListResource{
		Name:        "google_apigee_environment_keyvaluemaps_entries",
		ProductName: "Apigee",
		Func:        NewApigeeEnvironmentKeyvaluemapsEntriesListResource,
	}.Register()
}

var _ list.ListResource = &ApigeeEnvironmentKeyvaluemapsEntriesListResource{}

type ApigeeEnvironmentKeyvaluemapsEntriesListResource struct {
	tpgresource.ListResourceMetadata
}

func NewApigeeEnvironmentKeyvaluemapsEntriesListResource() list.ListResource {
	listR := &ApigeeEnvironmentKeyvaluemapsEntriesListResource{}
	listR.TypeName = "google_apigee_environment_keyvaluemaps_entries"
	listR.SDKv2Resource = ResourceApigeeEnvironmentKeyvaluemapsEntries()
	listR.ListConfigFields = []tpgresource.ListConfigField{
		{Name: "env_keyvaluemap_id", Kind: tpgresource.ListConfigKindString, Optional: false},
	}
	return listR
}

// ApigeeEnvironmentKeyvaluemapsEntriesListModel matches ListResourceMetadata.ListConfigFields (tfsdk names and types).
type ApigeeEnvironmentKeyvaluemapsEntriesListModel struct {
	EnvKeyvaluemapId types.String `tfsdk:"env_keyvaluemap_id"`
}

func (listR *ApigeeEnvironmentKeyvaluemapsEntriesListResource) List(ctx context.Context, listReq list.ListRequest, stream *list.ListResultsStream) {
	var data ApigeeEnvironmentKeyvaluemapsEntriesListModel
	diags := listReq.Config.Get(ctx, &data)
	if diags.HasError() {
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}
	if listR.Client == nil {
		diags = append(diags, diag.NewErrorDiagnostic(
			"Provider not configured",
			"The Google provider client is not available; ensure the provider is configured (e.g. credentials and default project).",
		))
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}
	envKeyvaluemapId := data.EnvKeyvaluemapId.ValueString()

	errStreamClosed := errors.New("stream closed")
	stream.Results = func(push func(list.ListResult) bool) {
		err := ListApigeeEnvironmentKeyvaluemapsEntriess(
			listR.Client,
			envKeyvaluemapId,
			func(rd *schema.ResourceData) error {
				result := listReq.NewListResult(ctx)

				if err := listR.SetResult(ctx, listReq.IncludeResource, &result, rd, "name"); err != nil {
					return err
				}

				if !push(result) {
					return errStreamClosed
				}
				return nil
			},
		)
		// A closed stream is not an error: return without pushing again.
		if err == nil || errors.Is(err, errStreamClosed) {
			return
		}
		diags.AddError("API Error", err.Error())
		result := listReq.NewListResult(ctx)
		result.Diagnostics = diags
		push(result)
	}
}

func ListApigeeEnvironmentKeyvaluemapsEntriess(config *transport_tpg.Config,
	envKeyvaluemapId string,
	callback func(*schema.ResourceData) error,
) error {
	resourceData := ResourceApigeeEnvironmentKeyvaluemapsEntries().Data(&terraform.InstanceState{})
	if envKeyvaluemapId != "" {
		if err := resourceData.Set("env_keyvaluemap_id", envKeyvaluemapId); err != nil {
			return fmt.Errorf("error setting env_keyvaluemap_id on temporary resource data: %w", err)
		}
	}

	url, err := tpgresource.ReplaceVars(resourceData, config, "{{ApigeeBasePath}}{{env_keyvaluemap_id}}/entries")
	if err != nil {
		return err
	}
	billingProject := ""
	if bp, err := tpgresource.GetBillingProject(resourceData, config); err == nil {
		billingProject = bp
	}

	userAgent, err := tpgresource.GenerateUserAgentString(resourceData, config.UserAgent)
	if err != nil {
		return err
	}

	return transport_tpg.ListPages(transport_tpg.ListPagesOptions{
		Config:         config,
		TempData:       resourceData,
		Resource:       ResourceApigeeEnvironmentKeyvaluemapsEntries(),
		ListURL:        url,
		BillingProject: billingProject,
		UserAgent:      userAgent,
		ItemName:       "keyValueEntries",
		Flattener: func(res map[string]interface{}, d *schema.ResourceData, config *transport_tpg.Config) error {
			headers := make(http.Header)
			var err error
			if v, ok := res["name"]; ok && v != nil {
				if err := d.Set("name", v); err != nil {
					return fmt.Errorf("error setting name: %w", err)
				}
			}
			if v, ok := res["env_keyvaluemap_id"]; ok && v != nil {
				if err := d.Set("env_keyvaluemap_id", v); err != nil {
					return fmt.Errorf("error setting env_keyvaluemap_id: %w", err)
				}
			}
			if err = ResourceApigeeEnvironmentKeyvaluemapsEntriesFlatten(d, config, res, config, userAgent, billingProject, url, headers); err != nil {
				return err
			}
			id, err := tpgresource.ReplaceVars(d, config, "{{env_keyvaluemap_id}}/entries/{{name}}")
			if err != nil {
				return fmt.Errorf("error constructing id: %w", err)
			}
			d.SetId(id)
			return nil
		},
		Callback: callback,
	})
}
