// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/oracledatabase/CloudExadataInfrastructureExascaleConfig.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/list_resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package oracledatabase

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/hashicorp/terraform-provider-google/google/registry"
	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google/google/transport"
)

func init() {
	registry.FrameworkListResource{
		Name:        "google_oracle_database_cloud_exadata_infrastructure_exascale_config",
		ProductName: "OracleDatabase",
		Func:        NewOracleDatabaseCloudExadataInfrastructureExascaleConfigListResource,
	}.Register()
}

var _ list.ListResource = &OracleDatabaseCloudExadataInfrastructureExascaleConfigListResource{}

type OracleDatabaseCloudExadataInfrastructureExascaleConfigListResource struct {
	tpgresource.ListResourceMetadata
}

func NewOracleDatabaseCloudExadataInfrastructureExascaleConfigListResource() list.ListResource {
	listR := &OracleDatabaseCloudExadataInfrastructureExascaleConfigListResource{}
	listR.TypeName = "google_oracle_database_cloud_exadata_infrastructure_exascale_config"
	listR.SDKv2Resource = ResourceOracleDatabaseCloudExadataInfrastructureExascaleConfig()
	listR.ListConfigFields = []tpgresource.ListConfigField{}
	return listR
}

// OracleDatabaseCloudExadataInfrastructureExascaleConfigListModel matches ListResourceMetadata.ListConfigFields (tfsdk names and types).
type OracleDatabaseCloudExadataInfrastructureExascaleConfigListModel struct {
}

func (listR *OracleDatabaseCloudExadataInfrastructureExascaleConfigListResource) List(ctx context.Context, listReq list.ListRequest, stream *list.ListResultsStream) {
	var data OracleDatabaseCloudExadataInfrastructureExascaleConfigListModel
	diags := listReq.Config.Get(ctx, &data)
	if diags.HasError() {
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}
	if listR.Client == nil {
		diags = append(diags, diag.NewErrorDiagnostic(
			"Provider not configured",
			"The Google provider client is not available; ensure the provider is configured (e.g. credentials and default project).",
		))
		stream.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}

	errStreamClosed := errors.New("stream closed")
	stream.Results = func(push func(list.ListResult) bool) {
		err := ListOracleDatabaseCloudExadataInfrastructureExascaleConfigs(
			listR.Client,
			func(rd *schema.ResourceData) error {
				result := listReq.NewListResult(ctx)

				if err := listR.SetResult(ctx, listReq.IncludeResource, &result, rd, "cloud_exadata_infrastructure"); err != nil {
					return err
				}

				if !push(result) {
					return errStreamClosed
				}
				return nil
			},
		)
		// A closed stream is not an error: return without pushing again.
		if err == nil || errors.Is(err, errStreamClosed) {
			return
		}
		diags.AddError("API Error", err.Error())
		result := listReq.NewListResult(ctx)
		result.Diagnostics = diags
		push(result)
	}
}

func ListOracleDatabaseCloudExadataInfrastructureExascaleConfigs(config *transport_tpg.Config,
	callback func(*schema.ResourceData) error,
) error {
	resourceData := ResourceOracleDatabaseCloudExadataInfrastructureExascaleConfig().Data(&terraform.InstanceState{})

	url, err := tpgresource.ReplaceVars(resourceData, config, "{{OracleDatabaseBasePath}}")
	if err != nil {
		return err
	}

	billingProject := ""
	if bp, err := tpgresource.GetBillingProject(resourceData, config); err == nil {
		billingProject = bp
	}

	userAgent, err := tpgresource.GenerateUserAgentString(resourceData, config.UserAgent)
	if err != nil {
		return err
	}

	return transport_tpg.ListPages(transport_tpg.ListPagesOptions{
		Config:         config,
		TempData:       resourceData,
		Resource:       ResourceOracleDatabaseCloudExadataInfrastructureExascaleConfig(),
		ListURL:        url,
		BillingProject: billingProject,
		UserAgent:      userAgent,
		ItemName:       "cloudExadataInfrastructureExascaleConfigs",
		Flattener: func(res map[string]interface{}, d *schema.ResourceData, config *transport_tpg.Config) error {
			headers := make(http.Header)
			var err error
			res, err = resourceOracleDatabaseCloudExadataInfrastructureExascaleConfigDecoder(d, config, res)
			if err != nil {
				return err
			}
			if res == nil {
				return fmt.Errorf("error decoding OracleDatabaseCloudExadataInfrastructureExascaleConfig from list response")
			}
			if v, ok := res["location"]; ok && v != nil {
				if err := d.Set("location", v); err != nil {
					return fmt.Errorf("error setting location: %w", err)
				}
			}
			if v, ok := res["cloudExadataInfrastructure"]; ok && v != nil {
				if err := d.Set("cloud_exadata_infrastructure", v); err != nil {
					return fmt.Errorf("error setting cloud_exadata_infrastructure: %w", err)
				}
			}
			project := ""
			if p, err := tpgresource.GetProject(d, config); err == nil {
				project = p
			}
			if err = ResourceOracleDatabaseCloudExadataInfrastructureExascaleConfigFlatten(d, config, res, config, project, userAgent, billingProject, url, headers); err != nil {
				return err
			}
			id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/cloudExadataInfrastructures/{{cloud_exadata_infrastructure}}")
			if err != nil {
				return fmt.Errorf("error constructing id: %w", err)
			}
			d.SetId(id)
			return nil
		},
		Callback: callback,
	})
}
