// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/oracledatabase/CloudExadataInfrastructureExascaleConfig.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package oracledatabase_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
)

var (
	_ = envvar.TestEnvVar
)

func TestAccOracleDatabaseCloudExadataInfrastructureExascaleConfigListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"cloud_exadata_infrastructure_id": fmt.Sprintf("ofake-test-tf-configured-exadata-%s", acctest.RandString(t, 10)),
		"deletion_protection":             false,
		"project":                         "oci-terraform-testing-prod",
		"random_suffix":                   randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckOracleDatabaseCloudExadataInfrastructureExascaleConfigDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccOracleDatabaseCloudExadataInfrastructureExascaleConfig_oracledatabaseCloudExadataInfrastructureExascaleConfigBasicExample(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_oracle_database_cloud_exadata_infrastructure_exascale_config.my_exascale_config",
						[]string{
							"cloud_exadata_infrastructure",
						},
					),
					listScope.Capture(map[string]string{}),
				),
			},
			{
				Query:           true,
				Config:          testAccOracleDatabaseCloudExadataInfrastructureExascaleConfig_oracledatabaseCloudExadataInfrastructureExascaleConfigBasicExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_oracle_database_cloud_exadata_infrastructure_exascale_config.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_oracle_database_cloud_exadata_infrastructure_exascale_config.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccOracleDatabaseCloudExadataInfrastructureExascaleConfig_oracledatabaseCloudExadataInfrastructureExascaleConfigBasicExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_oracle_database_cloud_exadata_infrastructure_exascale_config" "list_query" {
    provider = google
	limit = 10000
    config {
    }
}
`, context)
}
