// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/monitoring/GenericService.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package monitoring_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
)

var (
	_ = envvar.TestEnvVar
)

func TestAccMonitoringGenericServiceListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"service_id":    "tf-test-my-service" + randomSuffix,
		"project":       envvar.GetTestProjectFromEnv(),
		"random_suffix": randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckMonitoringGenericServiceDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccMonitoringGenericService_monitoringServiceExampleExample(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_monitoring_service.my_service",
						[]string{
							"name",
							"service_id",
						},
					),
					listScope.Capture(map[string]string{}),
				),
			},
			{
				Query:           true,
				Config:          testAccMonitoringGenericService_monitoringServiceExampleExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_monitoring_service.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_monitoring_service.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccMonitoringGenericService_monitoringServiceExampleExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_monitoring_service" "list_query" {
    provider = google
	limit = 10000
    config {
    }
}
`, context)
}
