// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/monitoring/Snooze.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package monitoring_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
)

var (
	_ = envvar.TestEnvVar
)

func TestAccMonitoringSnoozeListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"alert_policy_display_name": "tf-test-My Alert Policy" + randomSuffix,
		"snooze_display_name":       "tf-test-My Snooze" + randomSuffix,
		"snooze_end_time":           time.Date(time.Now().Year(), 12, 31, 0, 0, 0, 0, time.UTC).AddDate(0, 0, 2).Format(time.RFC3339),
		"snooze_start_time":         time.Date(time.Now().Year(), 12, 31, 0, 0, 0, 0, time.UTC).AddDate(0, 0, 1).Format(time.RFC3339),
		"project":                   envvar.GetTestProjectFromEnv(),
		"random_suffix":             randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccMonitoringSnooze_monitoringSnoozeBasicExample(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_monitoring_snooze.snooze",
						[]string{
							"name",
						},
					),
					listScope.Capture(map[string]string{}),
				),
			},
			{
				Query:           true,
				Config:          testAccMonitoringSnooze_monitoringSnoozeBasicExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_monitoring_snooze.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_monitoring_snooze.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccMonitoringSnooze_monitoringSnoozeBasicExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_monitoring_snooze" "list_query" {
    provider = google
	limit = 10000
    config {
    }
}
`, context)
}
