// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/cloudbuild/Trigger.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package cloudbuild_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
)

var (
	_ = envvar.TestEnvVar
)

func TestAccCloudBuildTriggerListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"location":      envvar.GetTestRegionFromEnv(),
		"project":       acctest.BootstrapProject(t, "tf-bt-list-", envvar.GetTestBillingAccountFromEnv(t), nil).ProjectId,
		"random_suffix": randomSuffix,
	}

	// Captured at create-step time and asserted against list-query results.
	var capturedDisplayName acctest.CapturedDisplayName

	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckCloudBuildTriggerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccCloudBuildTrigger_cloudbuildTriggerFilenameExample(context),
				Check: resource.ComposeTestCheckFunc(
					capturedDisplayName.CaptureCheck(
						"google_cloudbuild_trigger.filename-trigger",
						[]string{
							"trigger_id",
						},
					),
				),
			},
			{
				Query:  true,
				Config: testAccCloudBuildTrigger_cloudbuildTriggerFilenameExampleListQuery(context),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_cloudbuild_trigger.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_cloudbuild_trigger.list_query",
						queryfilter.ByDisplayName(capturedDisplayName.ExpectKnownValue()),
						capturedDisplayName.ExpectKnownValue(),
					),
				},
			},
		},
	})
}

func testAccCloudBuildTrigger_cloudbuildTriggerFilenameExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_cloudbuild_trigger" "list_query" {
    provider = google
    config {
        location = "%{location}"
        project = "%{project}"
    }
}
`, context)
}
