// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/fwprovider/framework_provider_mmv1_resources.go.tmpl
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package fwprovider

import (
	"github.com/hashicorp/terraform-plugin-framework/list"

	"github.com/hashicorp/terraform-provider-google/google/services/cloudbuild"
	"github.com/hashicorp/terraform-provider-google/google/services/cloudrun"
	"github.com/hashicorp/terraform-provider-google/google/services/resourcemanager"
)

func listResourceFunc(lr list.ListResource) func() list.ListResource {
	return func() list.ListResource { return lr }
}

// generatedListResources registers MMv1-generated list resources (generate_list_resource in YAML).
var generatedListResources = []func() list.ListResource{
	listResourceFunc(cloudbuild.NewCloudBuildTriggerListResource()),
	listResourceFunc(cloudrun.NewCloudRunServiceListResource()),
}

var handwrittenListResources = []func() list.ListResource{
	listResourceFunc(resourcemanager.NewGoogleServiceAccountListResource()),
	listResourceFunc(resourcemanager.NewGoogleProjectServiceListResource()),
}
