// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/fwprovider/framework_provider_mmv1_resources.go
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package fwprovider

import (
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-provider-google/google/services/compute"
)

// TODO: LOOK INTO HOW WE'D GENERATE THIS THE LIST OF LISTRESOURCES
// ListResources
var generatedListResources = map[string]list.ListResource{}

var handwrittenListResources = map[string]list.ListResource{
	"google_compute_instance": compute.NewComputeInstanceListResource(),
}
