name: TeamCity: Create empty branch off tip of main to aid nightly-testing


# Comment here about why this GHA exists...

on:
    schedule:
        - cron: '0 4 * * *'

jobs:
  create-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Create Nightly Test Branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'UTC-nightly-test-${{ steps.date.outputs.date }}'